<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>RohreZuschnittOptimierung</AssemblyName>
    <RootNamespace>RohreZuschnittOptimierung</RootNamespace>
    <ApplicationIcon />
    <AssemblyTitle>Rohre Zuschnitt Optimierung</AssemblyTitle>
    <Product>Rohre Zuschnitt Optimierung</Product>
    <Version>1.0.1</Version>
    <AssemblyVersion>1.0.0.1</AssemblyVersion>
    <FileVersion>1.0.0.1</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PDFsharp" Version="6.2.0" />
    <PackageReference Include="UglyToad.PdfPig" Version="1.7.0-custom-5" />
  </ItemGroup>

</Project>
